export const reportTypes = [
  {
    id: 'phishing',
    icon: '🎣',
    title: 'Hameçonnage (Phishing)',
    description: 'Email, SMS ou message frauduleux imitant une organisation légitime pour voler vos informations.',
    examples: ['Email bancaire suspect', 'SMS de livraison frauduleux', 'Faux support technique'],
    color: 'bg-red-50',
    borderColor: 'border-red-200',
    iconColor: 'text-red-600',
  },
  {
    id: 'romance',
    icon: '💔',
    title: 'Arnaque aux sentiments',
    description: 'Quelqu\'un crée une relation émotionnelle en ligne pour vous soutirer de l\'argent ou des informations.',
    examples: ['Faux profil sur site de rencontre', 'Demande d\'argent après relation en ligne', 'Chantage affectif'],
    color: 'bg-pink-50',
    borderColor: 'border-pink-200',
    iconColor: 'text-pink-600',
  },
  {
    id: 'investment',
    icon: '📈',
    title: 'Arnaque à l\'investissement',
    description: 'Promesses de gains financiers rapides ou de rendements exceptionnels qui sont trop beaux pour être vrais.',
    examples: ['Faux trading crypto', 'Investissement immobilier frauduleux', 'Système pyramidal'],
    color: 'bg-green-50',
    borderColor: 'border-green-200',
    iconColor: 'text-green-600',
  },
  {
    id: 'fake-job',
    icon: '💼',
    title: 'Arnaque à l\'emploi',
    description: 'Fausses offres d\'emploi demandant de l\'argent ou des informations personnelles.',
    examples: ['Travail à domicile rémunéré', 'Faux stage avec frais', 'Emploi nécessitant un paiement initial'],
    color: 'bg-blue-50',
    borderColor: 'border-blue-200',
    iconColor: 'text-blue-600',
  },
  {
    id: 'identity',
    icon: '🎭',
    title: 'Usurpation d\'identité',
    description: 'Quelqu\'un utilise vos informations personnelles sans votre consentement.',
    examples: ['Compte créé en votre nom', 'Utilisation frauduleuse de pièces d\'identité'],
    color: 'bg-purple-50',
    borderColor: 'border-purple-200',
    iconColor: 'text-purple-600',
  },
  {
    id: 'fake-shop',
    icon: '🛒',
    title: 'Faux site marchand',
    description: 'Site e-commerce frauduleux qui ne livre jamais les produits commandés.',
    examples: ['Site de vente trop alléchant', 'Contrefaçon', 'Paiement non sécurisé'],
    color: 'bg-yellow-50',
    borderColor: 'border-yellow-200',
    iconColor: 'text-yellow-600',
  },
  {
    id: 'lottery',
    icon: '🎰',
    title: 'Arnaque à la loterie',
    description: 'Notification de gain à une loterie à laquelle vous n\'avez jamais participé.',
    examples: ['Faux gain EuroMillions', 'Héritage inattendu', 'Frais de déblocage de fonds'],
    color: 'bg-amber-50',
    borderColor: 'border-amber-200',
    iconColor: 'text-amber-600',
  },
  {
    id: 'tech-support',
    icon: '🖥️',
    title: 'Faux support technique',
    description: 'Quelqu\'un prétend être du support technique pour accéder à votre ordinateur ou vous facturer des services inutiles.',
    examples: ['Pop-up d\'alerte virus', 'Appel téléphonique non sollicité', 'Prise de contrôle à distance'],
    color: 'bg-cyan-50',
    borderColor: 'border-cyan-200',
    iconColor: 'text-cyan-600',
  },
  {
    id: 'harassment',
    icon: '😤',
    title: 'Harcèlement en ligne',
    description: 'Messages menaçants, intimidations ou comportements abusifs sur internet.',
    examples: ['Cyberharcèlement', 'Menaces', 'Chantage'],
    color: 'bg-rose-50',
    borderColor: 'border-rose-200',
    iconColor: 'text-rose-600',
  },
  {
    id: 'other',
    icon: '⚠️',
    title: 'Autre type d\'arnaque',
    description: 'Tout autre type de fraude ou d\'arnaque que vous avez rencontrée.',
    examples: ['Fausse application', 'Arnaque au président', 'Autre'],
    color: 'bg-slate-50',
    borderColor: 'border-slate-200',
    iconColor: 'text-slate-600',
  },
];